# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dcc6905cf5bfa8cf6a7e5694afa458c31359cd0fc0cc5f41424f2ec4e06dc5ff260d641dd611f3f6c620084fd6317feea1d6da47b7731bf67d3c45540d748b0

test:
  secret_key_base: b981803cb5e8e55f8168203e7b4a5aea435748eda81048a89ebd869c7992f03752bba81a6435b9c1089e51375bdd4524c66eccf299f33a9b1f4659132eea00c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
